import type { Metadata } from "next";
import { Suspense } from "react";
import { SiteFrame } from "../../site-shell";
import { FeedbackTrainer } from "./feedback-trainer";

export const metadata: Metadata = {
  title: "Coaching feedback",
  description: "A sample Clash Royale coaching result with three randomized practice pointers.",
};

export default function CoachingFeedbackPage() {
  return (
    <SiteFrame
      active="coaching"
      eyebrow=""
      title="Coaching feedback"
      intro=""
      highlights={[]}
      footerNote="This is a local prototype. The three pointers are selected from a general coaching list rather than generated by video analysis."
      showHero={false}
      showSources={false}
    >
      <Suspense fallback={<div className="coaching-feedback-loading">Loading your feedback...</div>}>
        <FeedbackTrainer />
      </Suspense>
    </SiteFrame>
  );
}
