"use client";
import Link from "next/link";
import { useEffect, useState, useSyncExternalStore, type ReactNode } from "react";
export const LESSON_KEY = "cr-guide-completed-lessons";
export const PROGRESS_EVENT = "cr-guide-progress";
let lastStoredLessons: string | null | undefined;
let cachedCompletedLessons: number[] = [];
const EMPTY_COMPLETED: number[] = [];
function normalizeCompleted(value: unknown) { return Array.isArray(value) ? [...new Set(value.filter((item): item is number => Number.isInteger(item) && item >= 1 && item <= 10))].sort((a,b) => a-b) : []; }
function readCompletedLessons() { let raw: string | null = null; try { raw = window.localStorage.getItem(LESSON_KEY); } catch { return []; } if (raw === lastStoredLessons) return cachedCompletedLessons; lastStoredLessons = raw; try { cachedCompletedLessons = normalizeCompleted(JSON.parse(raw || "[]")); } catch { cachedCompletedLessons = []; } return cachedCompletedLessons; }
export function useCompletedLessons() { return useSyncExternalStore((onStoreChange) => { window.addEventListener("storage", onStoreChange); window.addEventListener(PROGRESS_EVENT, onStoreChange); return () => { window.removeEventListener("storage", onStoreChange); window.removeEventListener(PROGRESS_EVENT, onStoreChange); }; }, readCompletedLessons, () => EMPTY_COMPLETED); }
export function FeatureGate({ required, children }: { required: number; children: ReactNode }) { const completed = useCompletedLessons(); if (completed.length >= required) return <>{children}</>; return <div className="locked-page"><div className="lock-icon">🔒</div><p className="eyebrow">Keep learning</p><h2>Unlock this feature</h2><p>Complete {required} lessons on the learning road to open this page.</p><Link className="lesson-button" href="/">View the learning road</Link><div className="lock-progress"><span style={{ width: `${Math.min(100, completed.length / required * 100)}%` }} /></div><small>{completed.length} of {required} lessons complete</small></div>; }
export function LessonRoad() { const [completed, setCompleted] = useState<number[]>([]); useEffect(() => { const refresh = () => { try { setCompleted(normalizeCompleted(JSON.parse(window.localStorage.getItem(LESSON_KEY) || "[]"))); } catch { setCompleted([]); } }; refresh(); window.addEventListener("storage", refresh); window.addEventListener(PROGRESS_EVENT, refresh); return () => { window.removeEventListener("storage", refresh); window.removeEventListener(PROGRESS_EVENT, refresh); }; }, []); const toggleCompletion = (id: number) => { const next = completed.includes(id) ? completed.filter((lessonId) => lessonId !== id) : [...completed, id].sort((a,b) => a-b); setCompleted(next); try { window.localStorage.setItem(LESSON_KEY, JSON.stringify(next)); } catch { /* Keep the current lesson state usable when storage is blocked. */ } window.dispatchEvent(new Event(PROGRESS_EVENT)); }; return <div className="learning-road"><div className="road-summary"><div><p className="eyebrow">Your learning road</p><h2>Play your way to better decisions.</h2></div><strong>{completed.length}/10 <span>lessons</span></strong></div><div className="road-track"><div className="road-fill" style={{ height: `${completed.length / 10 * 100}%` }} />{Array.from({length:10},(_,i)=>{const id=i+1, done=completed.includes(id), available=id===1||completed.includes(id-1); return <div className={`lesson-node ${done?"done":""} ${available?"available":"locked"}`} key={id}><div className="node-dot">{done?"✓":available?id:"🔒"}</div><div className="lesson-copy"><span>Lesson {String(id).padStart(2,"0")}</span><h3>{id===1?"Splash damage basics":"Scenario coming soon"}</h3><p>{id===1?"Learn when to use a splash troop against a swarm.":"This mini scenario is still being designed."}</p>{(available||done)?<div className="lesson-actions">{id===1&&available?<a className="lesson-button" href="./gameplay_prototype.html">Play scenario <span>→</span></a>:null}<button type="button" className="complete-button" aria-pressed={done} onClick={()=>toggleCompletion(id)}>{done?"Mark incomplete":"Mark complete"}</button></div>:null}{done?<small className="complete-label">Completed · next lesson unlocked</small>:null}</div></div>})}</div></div>; }
